// src/react/components/core/EmailInput.tsx
/**
 * EmailInput - Granular email input component for authentication
 * Features: validation, WebAuthn autocomplete, conditional authentication trigger
 *
 * Ported from `src/svelte/components/core/EmailInput.svelte`. Controlled component
 * (React idiom) rather than Svelte's `bind:value` -- callers own `value` and pass
 * `onChange` to update it, matching how `SignInCore.tsx` drives this component.
 *
 * Note: the Svelte version styles its `<label>` with a bare `label { ... }` selector,
 * which Svelte's per-component scoping keeps local to this component. Plain CSS has no
 * such scoping, so the React port uses an explicit `.email-input-label` class instead
 * to avoid leaking a bare `label` rule onto a consumer's entire page.
 */
import type { ChangeEvent, FocusEvent } from 'react';
import { useEffect, useRef } from 'react';
import { m } from '../../../core/utils/i18n.js';
import './EmailInput.css';

export interface EmailInputProps {
  value?: string;
  placeholder?: string;
  disabled?: boolean;
  required?: boolean;
  error?: string | null;
  label?: string;
  showLabel?: boolean;
  enableWebAuthn?: boolean;
  debounceMs?: number;
  className?: string;
  onChange?: (payload: { value: string }) => void;
  onConditionalAuth?: (payload: { email: string }) => void;
  onFocus?: (payload: { value: string }) => void;
  onBlur?: (payload: { value: string }) => void;
}

function isValidEmail(email: string): boolean {
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  return emailRegex.test(email);
}

function getDisplayText(key: string): string {
  try {
    const messageFunction = (m as unknown as Record<string, () => string>)[key];
    if (typeof messageFunction === 'function') {
      return messageFunction();
    }
    return key;
  } catch {
    console.warn(`Translation key "${key}" not found in Paraglide messages`);
    return key;
  }
}

export function EmailInput({
  value = '',
  placeholder = '',
  disabled = false,
  required = true,
  error = null,
  label = '',
  showLabel = true,
  enableWebAuthn = true,
  debounceMs = 1000,
  className = '',
  onChange,
  onConditionalAuth,
  onFocus,
  onBlur
}: EmailInputProps) {
  const emailChangeTimeout = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    return () => {
      if (emailChangeTimeout.current) {
        clearTimeout(emailChangeTimeout.current);
      }
    };
  }, []);

  const handleInput = (event: ChangeEvent<HTMLInputElement>) => {
    const newValue = event.target.value;
    onChange?.({ value: newValue });

    if (emailChangeTimeout.current) {
      clearTimeout(emailChangeTimeout.current);
    }

    if (enableWebAuthn && newValue.trim() && !disabled) {
      emailChangeTimeout.current = setTimeout(() => {
        if (isValidEmail(newValue)) {
          onConditionalAuth?.({ email: newValue });
        }
      }, debounceMs);
    }
  };

  const handleFocus = (event: FocusEvent<HTMLInputElement>) => {
    onFocus?.({ value: event.target.value });
  };

  const handleBlur = (event: FocusEvent<HTMLInputElement>) => {
    onBlur?.({ value: event.target.value });
  };

  const inputClasses = error ? 'input-brand error' : 'input-brand';
  const displayPlaceholder = getDisplayText(placeholder || 'email.placeholder');
  const displayLabel = getDisplayText(label || 'email.label');

  return (
    <div className={`space-y-2 ${className}`}>
      {showLabel && (
        <label
          htmlFor="email-input"
          className="email-input-label block text-sm font-medium text-gray-700"
        >
          {displayLabel}
        </label>
      )}

      <input
        id="email-input"
        type="email"
        className={`w-full ${inputClasses}`}
        value={value}
        onChange={handleInput}
        onFocus={handleFocus}
        onBlur={handleBlur}
        placeholder={displayPlaceholder}
        disabled={disabled}
        required={required}
        autoComplete={enableWebAuthn ? 'email webauthn' : 'email'}
      />

      {error && (
        <div className="text-sm mt-1 text-semantic-error-600" role="alert">
          {error}
        </div>
      )}
    </div>
  );
}

// src/components/core/EmailInput.svelte
<!--
  EmailInput - Granular email input component for authentication
  Features: validation, WebAuthn autocomplete, conditional authentication trigger
-->
<script lang="ts">
import { m } from '../../utils/i18n';
import { createEventDispatcher } from 'svelte';


  interface Props {
    // Props
    value?: string;
    placeholder?: string;
    disabled?: boolean;
    required?: boolean;
    error?: string | null;
    label?: string;
    showLabel?: boolean;
    enableWebAuthn?: boolean;
    debounceMs?: number;
    className?: string;
  }

  let {
    value = $bindable(''),
    placeholder = '',
    disabled = false,
    required = true,
    error = null,
    label = '',
    showLabel = true,
    enableWebAuthn = true,
    debounceMs = 1000,
    className = ''
  }: Props = $props();

// Events
const dispatch = createEventDispatcher<{
  change: { value: string };
  conditionalAuth: { email: string };
  focus: { value: string };
  blur: { value: string };
}>();

// Internal state
let emailChangeTimeout: ReturnType<typeof setTimeout> | null = null;

// Email validation
function isValidEmail(email: string): boolean {
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  return emailRegex.test(email);
}

// Handle input changes
function handleInput(event: Event) {
  const target = event.target as HTMLInputElement;
  value = target.value;
  
  // Dispatch immediate change
  dispatch('change', { value });

  // Clear previous timeout
  if (emailChangeTimeout) {
    clearTimeout(emailChangeTimeout);
  }

  // Debounce conditional auth trigger
  if (enableWebAuthn && value.trim() && !disabled) {
    emailChangeTimeout = setTimeout(() => {
      if (isValidEmail(value)) {
        dispatch('conditionalAuth', { email: value });
      }
    }, debounceMs);
  }
}

function handleFocus(event: Event) {
  const target = event.target as HTMLInputElement;
  dispatch('focus', { value: target.value });
}

function handleBlur(event: Event) {
  const target = event.target as HTMLInputElement;
  dispatch('blur', { value: target.value });
}

function getInputClasses(): string {
  if (error) {
    return "input-brand error";
  }
  return "input-brand";
}


// Helper function to get display text from Paraglide
function getDisplayText(key: string): string {
  try {
    const messageFunction = (m as unknown as {[key: string]: () => string})[key];
    if (typeof messageFunction === 'function') {
      return messageFunction();
    }
    // Fallback to key if function doesn't exist
    return key;
  } catch (error) {
    console.warn(`Translation key "${key}" not found in Paraglide messages`);
    return key;
  }
}
// Reactive values for i18n
let displayPlaceholder = $derived(getDisplayText(placeholder || 'email.placeholder'));
let displayLabel = $derived(getDisplayText(label || 'email.label'));
</script>

<div class="space-y-2 {className}">
  {#if showLabel}
    <label for="email-input" class="block text-sm font-medium text-gray-700 dark:text-gray-300">
      {displayLabel}
    </label>
  {/if}
  
  <input
    id="email-input"
    type="email"
    class="w-full {getInputClasses()}"
    bind:value
    oninput={handleInput}
    onfocus={handleFocus}
    onblur={handleBlur}
    placeholder={displayPlaceholder}
    {disabled}
    {required}
    autocomplete={enableWebAuthn ? "email webauthn" : "email"}
  />
  
  {#if error}
    <div class="text-sm mt-1 text-semantic-error-600" role="alert">
      {error}
    </div>
  {/if}
</div>

<style>
  label {
    color: var(--color-text-secondary);
  }
</style>
