// src/svelte/components/core/AuthStateMessage.svelte
<!--
  AuthStateMessage - Component for displaying authentication status and error messages
  Features: different message types, icons, animations, accessibility, Paraglide i18n support
-->
<script lang="ts">
  import { run } from 'svelte/legacy';

import { m } from '@thepia/flows-auth';


  interface Props {
    // Props
    type?: 'error' | 'success' | 'info' | 'warning';
    message?: string;
    tKey?: string; // Translation key for Paraglide i18n
    showIcon?: boolean;
    dismissible?: boolean;
    className?: string;
    animate?: boolean;
    variant?: 'default' | 'pin-status';
    children?: import('svelte').Snippet;
  }

  let {
    type = 'info',
    message = '',
    tKey = '',
    showIcon = true,
    dismissible = false,
    className = '',
    animate = true,
    variant = 'default',
    children
  }: Props = $props();

// Internal state
let visible = $state(true);



function getDisplayMessage(): string {
  // If explicit message is provided, use it
  if (message) return message;

  // If tKey is provided, use Paraglide bracket notation for dot keys
  if (tKey) {
    // Use bracket notation to access Paraglide message functions with dot keys
    const messageFunction = (m as unknown as {[key: string]: () => string})[tKey];
    if (typeof messageFunction === 'function') {
      return messageFunction();
    } else {
      console.warn(`AuthStateMessage: Unknown tKey "${tKey}"`);
      return tKey; // Fallback to showing the key itself
    }
  }

  return '';
}

// SVG icon mapping - simple monochrome
const icons = {
  error: `<svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor"><path d="M8 1a7 7 0 1 0 0 14A7 7 0 0 0 8 1zM7 4a1 1 0 1 1 2 0v3a1 1 0 1 1-2 0V4zm1 8a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/></svg>`,
  success: `<svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor"><path d="M8 1a7 7 0 1 0 0 14A7 7 0 0 0 8 1zm3.354 5.854-4 4a.5.5 0 0 1-.708 0l-2-2a.5.5 0 1 1 .708-.708L7 9.793l3.646-3.647a.5.5 0 0 1 .708.708z"/></svg>`,
  info: `<svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor"><path d="M8 1a7 7 0 1 0 0 14A7 7 0 0 0 8 1zm0 3a1 1 0 0 1 1 1v4a1 1 0 1 1-2 0V5a1 1 0 0 1 1-1zm0 8a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/></svg>`,
  warning: `<svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor"><path d="M8 1a7 7 0 1 0 0 14A7 7 0 0 0 8 1zM7 4a1 1 0 1 1 2 0v3a1 1 0 1 1-2 0V4zm1 8a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/></svg>`
};

function dismiss() {
  if (dismissible) {
    visible = false;
  }
}

// Computed message - use Paraglide message functions directly
let displayMessage = $derived(getDisplayMessage());
// Check if we have slot content
let hasSlotContent = $derived(children);
// Auto-dismiss for success messages
run(() => {
    if (type === 'success' && displayMessage) {
    setTimeout(() => {
      if (dismissible) dismiss();
    }, 5000);
  }
  });
</script>

{#if visible && (displayMessage || hasSlotContent)}
  <div
    class="auth-message type-{type} variant-{variant} {className}"
    class:animate
    role={type === 'error' ? 'alert' : 'status'}
    aria-live={type === 'error' ? 'assertive' : 'polite'}
  >
    <div class="flex items-start gap-2">
      {#if showIcon}
        <span class="shrink-0 text-base mt-px" aria-hidden="true">
          {@html icons[type]}
        </span>
      {/if}

      <span class="flex-1 break-words text-left">
        {#if hasSlotContent}
          {@render children?.()}
        {:else}
          {displayMessage}
        {/if}
      </span>

      {#if dismissible}
        <button
          class="dismiss-button shrink-0"
          onclick={dismiss}
          aria-label="Dismiss message"
        >
          ×
        </button>
      {/if}
    </div>
  </div>
{/if}

<style>
  .auth-message {
    padding: 8px 0 0 0;
    font-size: 14px;
    line-height: 1.5;
    color: var(--color-text-primary, currentColor);
  }

  .auth-message.animate {
    animation: slideIn 0.3s ease-out;
  }

  @keyframes slideIn {
    from {
      opacity: 0;
      transform: translateY(-10px);
    }
    to {
      opacity: 1;
      transform: translateY(0);
    }
  }

  .dismiss-button {
    background: none;
    border: none;
    font-size: 18px;
    font-weight: 600;
    cursor: pointer;
    padding: 0;
    line-height: 1;
    opacity: 0.6;
    transition: opacity 0.2s;
  }

  .dismiss-button:hover {
    opacity: 1;
  }

  /* Message types - clean styling, no default backgrounds/borders */
  .type-error {
    color: var(--color-text-error, #dc2626);
  }

  .type-success {
    color: var(--color-text-success, #059669);
  }

  .type-info {
    color: var(--color-text-info, #0369a1);
  }

  .type-warning {
    color: var(--color-text-warning, #d97706);
  }

  /* Pin status variant - matches SignInCore pin-status-message styling */
  .variant-pin-status {
    padding: 12px 16px;
    margin: 12px 0;
    background: #f0f9ff;
    border: 1px solid #bae6fd;
    border-radius: 8px;
    font-size: 14px;
    color: #0369a1;
    line-height: 1.4;
  }

  /* Pin direct link styles (for buttons within pin-status variant) */
  .variant-pin-status :global(.pin-direct-link) {
    background: none;
    border: none;
    color: #0369a1;
    font-size: inherit;
    font-weight: 500;
    text-decoration: underline;
    cursor: pointer;
    padding: 0;
    margin: 0 0 0 4px;
    transition: color 0.2s;
  }

  .variant-pin-status :global(.pin-direct-link:hover:not(:disabled)) {
    color: #075985;
  }

  .variant-pin-status :global(.pin-direct-link:disabled) {
    opacity: 0.6;
    cursor: not-allowed;
    text-decoration: none;
  }

</style>

// src/react/components/core/AuthStateMessage.tsx
/**
 * AuthStateMessage - Component for displaying authentication status and error messages
 * Features: different message types, icons, animations, accessibility, Paraglide i18n support
 *
 * Ported from `src/svelte/components/core/AuthStateMessage.svelte`. Behavior parity:
 * - `message` wins over `tKey` (explicit message > translated lookup).
 * - Auto-dismisses `success` messages after 5s when `dismissible` is true.
 * - Same class names / CSS custom property hooks as the Svelte version (see
 *   `./AuthStateMessage.css`), so consumers styling one target keep parity with the other.
 */
import type { ReactNode } from 'react';
import { useEffect, useState } from 'react';
import { m } from '../../../core/utils/i18n.js';
import './AuthStateMessage.css';

export interface AuthStateMessageProps {
  type?: 'error' | 'success' | 'info' | 'warning';
  message?: string;
  /** Translation key for Paraglide i18n (bracket-accessed against `m`). */
  tKey?: string;
  showIcon?: boolean;
  dismissible?: boolean;
  className?: string;
  animate?: boolean;
  variant?: 'default' | 'pin-status';
  children?: ReactNode;
}

// SVG icon mapping - simple monochrome (identical markup to the Svelte version)
const icons: Record<NonNullable<AuthStateMessageProps['type']>, string> = {
  error:
    '<svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor"><path d="M8 1a7 7 0 1 0 0 14A7 7 0 0 0 8 1zM7 4a1 1 0 1 1 2 0v3a1 1 0 1 1-2 0V4zm1 8a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/></svg>',
  success:
    '<svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor"><path d="M8 1a7 7 0 1 0 0 14A7 7 0 0 0 8 1zm3.354 5.854-4 4a.5.5 0 0 1-.708 0l-2-2a.5.5 0 1 1 .708-.708L7 9.793l3.646-3.647a.5.5 0 0 1 .708.708z"/></svg>',
  info: '<svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor"><path d="M8 1a7 7 0 1 0 0 14A7 7 0 0 0 8 1zm0 3a1 1 0 0 1 1 1v4a1 1 0 1 1-2 0V5a1 1 0 0 1 1-1zm0 8a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/></svg>',
  warning:
    '<svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor"><path d="M8 1a7 7 0 1 0 0 14A7 7 0 0 0 8 1zM7 4a1 1 0 1 1 2 0v3a1 1 0 1 1-2 0V4zm1 8a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/></svg>'
};

function getDisplayMessage(message: string, tKey: string): string {
  if (message) return message;

  if (tKey) {
    const messageFunction = (m as unknown as Record<string, () => string>)[tKey];
    if (typeof messageFunction === 'function') {
      return messageFunction();
    }
    console.warn(`AuthStateMessage: Unknown tKey "${tKey}"`);
    return tKey;
  }

  return '';
}

export function AuthStateMessage({
  type = 'info',
  message = '',
  tKey = '',
  showIcon = true,
  dismissible = false,
  className = '',
  animate = true,
  variant = 'default',
  children
}: AuthStateMessageProps) {
  const [visible, setVisible] = useState(true);
  const displayMessage = getDisplayMessage(message, tKey);
  const hasSlotContent = Boolean(children);

  const dismiss = () => {
    if (dismissible) {
      setVisible(false);
    }
  };

  // Auto-dismiss for success messages (mirrors the Svelte `run(() => {...})` block).
  useEffect(() => {
    if (type === 'success' && displayMessage && dismissible) {
      const timeout = setTimeout(() => {
        setVisible(false);
      }, 5000);
      return () => clearTimeout(timeout);
    }
    return undefined;
  }, [type, displayMessage, dismissible]);

  if (!visible || !(displayMessage || hasSlotContent)) {
    return null;
  }

  return (
    <div
      className={`auth-message type-${type} variant-${variant} ${animate ? 'animate' : ''} ${className}`}
      role={type === 'error' ? 'alert' : 'status'}
      aria-live={type === 'error' ? 'assertive' : 'polite'}
    >
      <div className="flex items-start gap-2">
        {showIcon && (
          <span
            className="shrink-0 text-base mt-px"
            aria-hidden="true"
            // biome-ignore lint/security/noDangerouslySetInnerHtml: fixed, non-user-controlled monochrome icon markup (same set as the Svelte version's {@html}).
            dangerouslySetInnerHTML={{ __html: icons[type] }}
          />
        )}

        <span className="flex-1 break-words text-left">
          {hasSlotContent ? children : displayMessage}
        </span>

        {dismissible && (
          <button
            type="button"
            className="dismiss-button shrink-0"
            onClick={dismiss}
            aria-label="Dismiss message"
          >
            ×
          </button>
        )}
      </div>
    </div>
  );
}
