// src/components/core/CodeInput.svelte
<!--
  CodeInput - Dedicated input component for verification codes
  Features: numeric input optimization, proper formatting, validation

  Non-Controlled approach where the value remains internal.
-->
<script lang="ts">
  import { run } from 'svelte/legacy';

import { createEventDispatcher } from 'svelte';
import { m } from '../../utils/i18n';

// Internal state (non-controlled)
let value = $state('');


  interface Props {
    // Props
    placeholder?: string;
    disabled?: boolean;
    required?: boolean;
    error?: string | null;
    label?: string;
    showLabel?: boolean;
    maxlength?: number;
    className?: string;
    autoAdvance?: boolean; // Auto-submit when code is complete
    showDigits?: boolean; // Show individual digit boxes instead of single input
    autoFocus?: boolean; // Auto-focus the input when component mounts
  }

  let {
    placeholder = '',
    disabled = false,
    required = true,
    error = null,
    label = '',
    showLabel = true,
    maxlength = 6,
    className = '',
    autoAdvance = false,
    showDigits = false,
    autoFocus = false
  }: Props = $props();

// Events
const dispatch = createEventDispatcher<{
  change: { value: string };
  focus: { value: string };
  blur: { value: string };
  complete: { value: string }; // Fired when code is complete (autoAdvance)
}>();

// Internal state for individual digits
let digits: string[] = $state(Array(maxlength).fill(''));
let inputRef: HTMLInputElement = $state();
let digitRefs: HTMLInputElement[] = $state([]);
let isUpdatingFromValue = $state(false);


// Internal state for tracking current input length
let currentLength = $state(0);
let internalValue = $state('');


// Handle input changes for single input mode
function handleInput(event: Event) {
  const target = event.target as HTMLInputElement;
  // Only allow numeric input
  const numericValue = target.value.replace(/[^0-9]/g, '');

  // Update the target to show filtered value
  target.value = numericValue;

  // Update value (exported prop) and internal tracking
  value = numericValue;
  internalValue = numericValue;
  currentLength = numericValue.length;

  // Only dispatch change when code is valid (exact length)
  if (numericValue.length === maxlength) {
    dispatch('change', { value: numericValue });

    if (autoAdvance) {
      dispatch('complete', { value: numericValue });
    }
  }
}

// Handle digit input for individual digit mode
function handleDigitInput(event: Event, index: number) {
  const target = event.target as HTMLInputElement;
  const numericValue = target.value.replace(/[^0-9]/g, '');

  // Only take the last character if multiple were entered
  const digit = numericValue.slice(-1);

  isUpdatingFromValue = true;
  digits[index] = digit;
  digits = [...digits]; // Trigger reactivity
  value = digits.join('');
  isUpdatingFromValue = false;

  // Auto-advance to next input
  if (digit && index < maxlength - 1) {
    const nextInput = digitRefs[index + 1];
    if (nextInput) {
      nextInput.focus();
    }
  }

  // Dispatch events
  dispatch('change', { value });

  // Auto-complete when all digits are filled
  if (autoAdvance && value.length === maxlength) {
    dispatch('complete', { value });
  }
}

// Handle keydown for individual digits (backspace navigation)
function handleDigitKeyDown(event: KeyboardEvent, index: number) {
  if (event.key === 'Backspace' && !digits[index] && index > 0) {
    // Move to previous input if current is empty
    const prevInput = digitRefs[index - 1];
    if (prevInput) {
      prevInput.focus();
    }
  }
}

// Handle paste for both single and digit modes
function handlePaste(event: ClipboardEvent) {
  event.preventDefault();
  const pastedText = event.clipboardData?.getData('text') || '';
  const numericValue = pastedText.replace(/[^0-9]/g, '').slice(0, maxlength);

  isUpdatingFromValue = true;
  value = numericValue;

  if (showDigits) {
    // Update individual digits
    for (let i = 0; i < maxlength; i++) {
      digits[i] = numericValue[i] || '';
    }
    digits = [...digits];
  }
  isUpdatingFromValue = false;

  dispatch('change', { value: numericValue });

  if (autoAdvance && numericValue.length === maxlength) {
    dispatch('complete', { value: numericValue });
  }
}

function handleFocus(event: Event) {
  const target = event.target as HTMLInputElement;
  // Auto-select all text for easier replacement
  target.select();
  dispatch('focus', { value });
}

function handleBlur(event: Event) {
  const target = event.target as HTMLInputElement;
  dispatch('blur', { value });
}

function getInputClasses(): string {
  const baseClasses = "input-brand text-center text-lg font-mono tracking-widest";
  if (error) {
    return `${baseClasses} error`;
  }
  return baseClasses;
}

// Auto-focus functionality
function focusInput() {
  if (showDigits && digitRefs[0]) {
    digitRefs[0].focus();
  } else if (inputRef) {
    inputRef.focus();
  }
}



// Helper function to get display text from Paraglide
function getDisplayText(key: string): string {
  try {
    const messageFunction = (m as unknown as {[key: string]: () => string})[key];
    if (typeof messageFunction === 'function') {
      return messageFunction();
    }
    // Fallback to key if function doesn't exist
    return key;
  } catch (error) {
    console.warn(`Translation key "${key}" not found in Paraglide messages`);
    return key;
  }
}
// Initialize digits array when maxlength changes
run(() => {
  if (showDigits && !isUpdatingFromValue) {
    const newDigits = Array(maxlength).fill('');
    // Update digits from current value
    if (value) {
      const chars = value.split('');
      for (let i = 0; i < maxlength; i++) {
        newDigits[i] = chars[i] || '';
      }
    }
    digits = newDigits;
  }
});
// Sync internal value with value prop for controlled mode
run(() => {
    if (value !== internalValue && value !== undefined) {
    internalValue = value;
    currentLength = value.length;
  }
  });
// Auto-focus on mount if enabled
run(() => {
    if (autoFocus) {
    setTimeout(focusInput, 0); // Use setTimeout to ensure DOM is ready
  }
  });
// Reactive values for i18n
let displayPlaceholder = $derived(getDisplayText(placeholder || 'code_placeholder'));
let displayLabel = $derived(getDisplayText(label || 'code_label'));
// Use existing translation keys for accessibility
let ariaLabel = $derived(`${m['code.label']()} (${maxlength} digits)`);
let helpText = $derived(`Enter ${maxlength}-digit verification code`);
</script>

<div class="space-y-2 {className}">
  {#if showLabel}
  <label for={showDigits ? "digit-0" : "code-input"} class="block text-sm text-left font-medium text-gray-700 dark:text-gray-300">
      {displayLabel} ({currentLength}/{maxlength})
    </label>
  {/if}

  <!-- Accessibility helper text -->
  <div id="code-help" class="sr-only">
    {helpText}
  </div>

  {#if showDigits}
    <!-- Individual digit inputs -->
    <div class="flex gap-2 justify-center">
      {#each Array(maxlength) as _, i}
        <input
          bind:this={digitRefs[i]}
          id="digit-{i}"
          type="text"
          class="w-12 h-12 text-center text-lg font-mono border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-blue-500 {error ? 'border-red-500' : ''}"
          bind:value={digits[i]}
          oninput={(e) => handleDigitInput(e, i)}
          onkeydown={(e) => handleDigitKeyDown(e, i)}
          onpaste={handlePaste}
          maxlength="1"
          {disabled}
          {required}
          autocomplete="one-time-code"
          inputmode="numeric"
          pattern="[0-9]"
          aria-label="{ariaLabel} digit {i + 1}"
          aria-describedby="code-help"
        />
      {/each}
    </div>
  {:else}
    <!-- Single input mode -->
    <input
      bind:this={inputRef}
      id="code-input"
      type="text"
      class="w-full {getInputClasses()}"
      value={value}
      oninput={handleInput}
      onfocus={handleFocus}
      onblur={handleBlur}
      onpaste={handlePaste}
      placeholder={displayPlaceholder}
      {disabled}
      {required}
      {maxlength}
      autocomplete="one-time-code"
      inputmode="numeric"
      pattern="[0-9]*"
      aria-label={ariaLabel}
      aria-describedby="code-help"
    />
  {/if}

  {#if error}
    <div class="text-sm mt-1 text-semantic-error-600" role="alert">
      {error}
    </div>
  {/if}
</div>

<style>
  label {
    color: var(--color-text-secondary);
  }

  /* Screen reader only content */
  .sr-only {
    position: absolute;
    width: 1px;
    height: 1px;
    padding: 0;
    margin: -1px;
    overflow: hidden;
    clip: rect(0, 0, 0, 0);
    white-space: nowrap;
    border: 0;
  }

  /* Individual digit input styling */
  .digit-input {
    transition: all 0.15s ease;
  }

  .digit-input:focus {
    transform: scale(1.05);
  }
</style>

// src/react/components/core/CodeInput.tsx
/**
 * CodeInput - Dedicated input component for verification codes
 * Features: numeric input optimization, proper formatting, validation
 *
 * Non-controlled approach where the value remains internal (ported from
 * `src/svelte/components/core/CodeInput.svelte`, matching its own doc comment).
 */
import type { ChangeEvent, ClipboardEvent, FocusEvent, KeyboardEvent } from 'react';
import { useEffect, useMemo, useRef, useState } from 'react';
import { m } from '../../../core/utils/i18n.js';
import './CodeInput.css';

export interface CodeInputProps {
  placeholder?: string;
  disabled?: boolean;
  required?: boolean;
  error?: string | null;
  label?: string;
  showLabel?: boolean;
  maxlength?: number;
  className?: string;
  /** Auto-submit when code is complete */
  autoAdvance?: boolean;
  /** Show individual digit boxes instead of single input */
  showDigits?: boolean;
  /** Auto-focus the input when component mounts */
  autoFocus?: boolean;
  onChange?: (payload: { value: string }) => void;
  onFocusChange?: (payload: { value: string }) => void;
  onBlurChange?: (payload: { value: string }) => void;
  /** Fired when code is complete (autoAdvance) */
  onComplete?: (payload: { value: string }) => void;
}

function getDisplayText(key: string): string {
  try {
    const messageFunction = (m as unknown as Record<string, () => string>)[key];
    if (typeof messageFunction === 'function') {
      return messageFunction();
    }
    return key;
  } catch {
    console.warn(`Translation key "${key}" not found in Paraglide messages`);
    return key;
  }
}

export function CodeInput({
  placeholder = '',
  disabled = false,
  required = true,
  error = null,
  label = '',
  showLabel = true,
  maxlength = 6,
  className = '',
  autoAdvance = false,
  showDigits = false,
  autoFocus = false,
  onChange,
  onFocusChange,
  onBlurChange,
  onComplete
}: CodeInputProps) {
  const [value, setValue] = useState('');
  const [digits, setDigits] = useState<string[]>(() => Array(maxlength).fill(''));
  const inputRef = useRef<HTMLInputElement | null>(null);
  const digitRefs = useRef<(HTMLInputElement | null)[]>([]);

  // Stable per-slot keys, independent of digit position/value, so re-renders
  // don't key digit boxes off their array index (see CodeInput port notes).
  const digitKeys = useMemo(
    () => Array.from({ length: maxlength }, () => Math.random().toString(36).slice(2)),
    [maxlength]
  );

  useEffect(() => {
    setDigits(Array(maxlength).fill(''));
  }, [maxlength]);

  useEffect(() => {
    if (!autoFocus) return undefined;
    const timeout = setTimeout(() => {
      if (showDigits && digitRefs.current[0]) {
        digitRefs.current[0].focus();
      } else {
        inputRef.current?.focus();
      }
    }, 0);
    return () => clearTimeout(timeout);
  }, [autoFocus, showDigits]);

  const handleInput = (event: ChangeEvent<HTMLInputElement>) => {
    const numericValue = event.target.value.replace(/[^0-9]/g, '');
    setValue(numericValue);

    if (numericValue.length === maxlength) {
      onChange?.({ value: numericValue });
      if (autoAdvance) {
        onComplete?.({ value: numericValue });
      }
    }
  };

  const handleDigitInput = (event: ChangeEvent<HTMLInputElement>, index: number) => {
    const numericValue = event.target.value.replace(/[^0-9]/g, '');
    const digit = numericValue.slice(-1);

    const nextDigits = [...digits];
    nextDigits[index] = digit;
    setDigits(nextDigits);
    const nextValue = nextDigits.join('');
    setValue(nextValue);

    if (digit && index < maxlength - 1) {
      digitRefs.current[index + 1]?.focus();
    }

    onChange?.({ value: nextValue });

    if (autoAdvance && nextValue.length === maxlength) {
      onComplete?.({ value: nextValue });
    }
  };

  const handleDigitKeyDown = (event: KeyboardEvent<HTMLInputElement>, index: number) => {
    if (event.key === 'Backspace' && !digits[index] && index > 0) {
      digitRefs.current[index - 1]?.focus();
    }
  };

  const handlePaste = (event: ClipboardEvent<HTMLInputElement>) => {
    event.preventDefault();
    const pastedText = event.clipboardData?.getData('text') || '';
    const numericValue = pastedText.replace(/[^0-9]/g, '').slice(0, maxlength);

    setValue(numericValue);

    if (showDigits) {
      const nextDigits = Array(maxlength).fill('');
      for (let i = 0; i < maxlength; i++) {
        nextDigits[i] = numericValue[i] || '';
      }
      setDigits(nextDigits);
    }

    onChange?.({ value: numericValue });

    if (autoAdvance && numericValue.length === maxlength) {
      onComplete?.({ value: numericValue });
    }
  };

  const handleFocus = (event: FocusEvent<HTMLInputElement>) => {
    // Auto-select all text for easier replacement.
    event.target.select();
    onFocusChange?.({ value });
  };

  const handleBlur = () => {
    onBlurChange?.({ value });
  };

  const inputClasses = `input-brand text-center text-lg font-mono tracking-widest${error ? ' error' : ''}`;
  const displayPlaceholder = getDisplayText(placeholder || 'code_placeholder');
  const displayLabel = getDisplayText(label || 'code_label');
  const ariaLabel = `${m['code.label']()} (${maxlength} digits)`;
  const helpText = `Enter ${maxlength}-digit verification code`;

  return (
    <div className={`space-y-2 ${className}`}>
      {showLabel && (
        <label
          htmlFor={showDigits ? 'digit-0' : 'code-input'}
          className="code-input-label block text-sm text-left font-medium text-gray-700"
        >
          {displayLabel} ({value.length}/{maxlength})
        </label>
      )}

      <div id="code-help" className="sr-only">
        {helpText}
      </div>

      {showDigits ? (
        <div className="flex gap-2 justify-center">
          {digitKeys.map((key, i) => (
            <input
              key={key}
              ref={(el) => {
                digitRefs.current[i] = el;
              }}
              id={`digit-${i}`}
              type="text"
              className={`digit-input${error ? ' error' : ''}`}
              value={digits[i] ?? ''}
              onChange={(e) => handleDigitInput(e, i)}
              onKeyDown={(e) => handleDigitKeyDown(e, i)}
              onPaste={handlePaste}
              maxLength={1}
              disabled={disabled}
              required={required}
              autoComplete="one-time-code"
              inputMode="numeric"
              pattern="[0-9]"
              aria-label={`${ariaLabel} digit ${i + 1}`}
              aria-describedby="code-help"
            />
          ))}
        </div>
      ) : (
        <input
          ref={inputRef}
          id="code-input"
          type="text"
          className={`w-full ${inputClasses}`}
          value={value}
          onChange={handleInput}
          onFocus={handleFocus}
          onBlur={handleBlur}
          onPaste={handlePaste}
          placeholder={displayPlaceholder}
          disabled={disabled}
          required={required}
          maxLength={maxlength}
          autoComplete="one-time-code"
          inputMode="numeric"
          pattern="[0-9]*"
          aria-label={ariaLabel}
          aria-describedby="code-help"
        />
      )}

      {error && (
        <div className="text-sm mt-1 text-semantic-error-600" role="alert">
          {error}
        </div>
      )}
    </div>
  );
}
