// src/components/core/PinEntryStep.svelte
<!--
  PinEntryStep - PIN code entry and verification step
  Isolated component for the pinEntry state
-->
<script lang="ts">
import { createEventDispatcher } from 'svelte';
import type { AuthMethod } from '../../types';
import type { SvelteAuthStore } from '../../types/svelte';
import CodeInput from './CodeInput.svelte';
import AuthButton from './AuthButton.svelte';
import AuthStateMessage from './AuthStateMessage.svelte';

export let authStore: SvelteAuthStore;

const dispatch = createEventDispatcher<{
  success: { user: any; method: AuthMethod };
}>();

// Reactive store subscription
$: store = authStore;
$: authConfig = $authStore?.config;

// Button config - only depends on fields needed for pinEntry
$: buttonConfig = (() => {
  const deps = [$authStore?.loading, $authStore?.emailCode];
  return authStore ? authStore.getButtonConfig() : null;
})();

// State message (includes API errors) - reactive to signInState and apiError changes
$: stateMessage = authStore && ($authStore.signInState || $authStore.apiError !== undefined) ? authStore.getStateMessageConfig() : null;

async function handleEmailCodeVerification() {
  console.log('🔐 handleEmailCodeVerification called', { emailCode: $authStore.emailCode });
  const code = $authStore.emailCode || '';
  if (!code.trim()) {
    console.log('❌ No code to verify');
    return;
  }
  console.log('✅ Verifying code:', code);

  try {
    const result = await authStore.verifyEmailCode(code);

    // verifyEmailCode returns SignInData with user and tokens, not a response with step
    if (result && result.user) {
      dispatch('success', {
        user: result.user,
        method: 'email-code' as AuthMethod
      });
    } else {
      throw new Error('Email code verification failed');
    }
  } catch (err: any) {
    console.error('❌ Email code verification failed in component:', err);
  }
}
</script>

<div class="email-code-input">
  <form on:submit|preventDefault={handleEmailCodeVerification}>
    <CodeInput
      on:change={(e) => {
        authStore.setEmailCode(e.detail.value);
      }}
      label="code.label"
      placeholder="code.placeholder"
      disabled={$authStore.loading}
      maxlength={authConfig?.emailCodeLength || 6}
    />

    {#if stateMessage}
      <AuthStateMessage
        type={stateMessage.type}
        tKey={stateMessage.textKey}
        showIcon={stateMessage.showIcon}
      />
    {/if}

    {#if buttonConfig}
      <div class="button-section">
        <AuthButton
          type="submit"
          buttonConfig={buttonConfig.primary}
          loading={$authStore.loading}
        />

        {#if buttonConfig.secondary}
          <AuthButton
            type="button"
            variant="secondary"
            buttonConfig={buttonConfig.secondary}
            loading={$authStore.loading}
            on:click={authStore.reset}
          />
        {/if}
      </div>
    {/if}
  </form>
</div>

// src/react/components/core/PinEntryStep.tsx
/**
 * PinEntryStep - PIN code entry and verification step
 * Isolated component for the `pinEntry` signInState.
 *
 * Ported from `src/svelte/components/core/PinEntryStep.svelte`.
 */
import type { FormEvent } from 'react';
import type { ComposedAuthStore } from '../../../core/stores/auth-store.js';
import type { AuthMethod, User } from '../../../core/types/index.js';
import { debug } from '../../../core/utils/debug.js';
import type { UseAuthStoreResult } from '../../hooks/useAuthStore.js';
import { useAuthStore } from '../../hooks/useAuthStore.js';
import { AuthButton } from './AuthButton.js';
import { AuthStateMessage } from './AuthStateMessage.js';
import { CodeInput } from './CodeInput.js';
import './PinEntryStep.css';

// `emailCode` is materialized at runtime by `ComposedAuthStore.getState()` (it's part of
// the UI sub-store) but missing from the plain `AuthStore` TS interface -- a real gap in
// `src/core/types/index.ts` flagged during the React port (see Phase C report). Widening
// the hook's return type locally here, rather than casting to `any` at every call site.
type AuthStoreResultWithEmailCode = UseAuthStoreResult & { emailCode: string };

export interface PinEntryStepProps {
  store?: ComposedAuthStore;
  onSuccess?: (payload: { user: User | null; method: AuthMethod }) => void;
}

export function PinEntryStep({ store: storeProp, onSuccess }: PinEntryStepProps) {
  const store = useAuthStore(storeProp) as AuthStoreResultWithEmailCode;
  const authConfig = store.getConfig?.();
  const buttonConfig = store.getButtonConfig();
  const stateMessage =
    store.signInState || store.apiError !== undefined ? store.getStateMessageConfig() : null;

  const handleEmailCodeVerification = async () => {
    const code = store.emailCode || '';
    if (!code.trim()) {
      debug('❌ No code to verify');
      return;
    }
    debug('✅ Verifying code:', code);

    try {
      const result = await store.verifyEmailCode(code);
      if (result?.user) {
        // `verifyEmailCode()` resolves with the raw `SignInData` shape (its nested `.user`
        // lacks `createdAt`/etc. that the core `User` type requires) -- read the canonical,
        // already-converted `User` off the store instead, same fix as `SignInCore`'s
        // `handlePasskeyAuth`.
        const user = store.getState().user;
        onSuccess?.({ user, method: 'email-code' as AuthMethod });
      } else {
        throw new Error('Email code verification failed');
      }
    } catch (err) {
      console.error('❌ Email code verification failed in component:', err);
    }
  };

  const handleSubmit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    void handleEmailCodeVerification();
  };

  return (
    <div className="email-code-input">
      <form onSubmit={handleSubmit}>
        <CodeInput
          onChange={(e) => store.setEmailCode(e.value)}
          label="code.label"
          placeholder="code.placeholder"
          disabled={store.loading}
          maxlength={authConfig?.emailCodeLength || 6}
        />

        {stateMessage && (
          <AuthStateMessage
            type={stateMessage.type}
            tKey={stateMessage.textKey}
            showIcon={stateMessage.showIcon}
          />
        )}

        {buttonConfig && (
          <div className="button-section">
            <AuthButton type="submit" buttonConfig={buttonConfig.primary} loading={store.loading} />

            {buttonConfig.secondary && (
              <AuthButton
                type="button"
                variant="secondary"
                buttonConfig={buttonConfig.secondary}
                loading={store.loading}
                onClick={() => store.reset()}
              />
            )}
          </div>
        )}
      </form>
    </div>
  );
}
